version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-server    # Name of the container
    ports:
      - "25565:25565"         # Ports
    environment:
      EULA: "TRUE"            # Accept the EULA
      TYPE: "FORGE"           # Type of minecraft
      VERSION: "1.21.4"       # Minecraft version
      MEMORY: "4G"            # Maximum memory used
      ONLINE_MODE: "FALSE"    # Allow users who have hacked minecraft
    volumes:
      - ./data:/data          # Server data volume
      - ./mods:/data/mods     # Server data mods
    restart: always