version: "3.8"
services:
  minecraft:
    image: itzg/minecraft-server:java8-multiarch
    container_name: minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      MEMORY: "4G"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./data:/data
      - ./mods:/data/mods
    restart: always